export interface User {
    id: string,
    username: string,
    name: string,
    avatar: string,
    password: string,
    vanity: string,
    email: string,
    is_verified: boolean,
    is_private: boolean,
    verified_email: boolean,
    bio: string,
    email_code: string,
    created_at: Date,
    updated_at: Date,
    verified_at: Date,
    permissions: object,
    suspended: boolean,
    suspended_date: Date,
    mfa: boolean,
    mfa_backup: string[]
}